[package]
name = "libsoxr"
version = "0.1.0"
authors = ["Reinier Balt <lrbalt@gmail.com>"]
description = "Wrapper for libsoxr (resampling library for sounds)"
repository = "https://github.com/lrbalt/libsoxr-rs"
keywords = ["audio", "sound", "resampling", "sox", "soxr"]
licence = "LGPL-2.0"

[dependencies]
